const express = require('express')
const connect = require('./connectionWithMdb/connect')
const {home, image, studentSection, studentSignup, student, examSection, studentMarks, examDateSheet, feesSection, manageFees, teacherSection, teacherAccount, teacherdata, allhomework, studenthomework} = require('./api-key/home')
const studentData = require('./api-key/studentData')
const studentProfile = require('./api-key/studentProfile')
const mark = require('./api-key/marks')
const update = require('./api-key/update')
const dateSheet = require('./api-key/dateSheet')
const dateSheetTable = require('./api-key/dateSheetTable')
const updateDateSheet = require('./api-key/updateDateSheet')
const signup = require('./api-key/signup')
const updatedata = require('./api-key/studentDataUpdate')
const deletes = require('./api-key/delete')
const fees = require('./api-key/fees')
const cookiesParser = require('cookie-parser')
const auth = require('./api-key/login')
const authpage = require('./api-key/auth')
const authMidleware = require('./midlwire/session')
const teacher = require('./api-key/teacher')
const path = require('path')
const teacherSignup = require('./api-key/teacherAccount')
const teacherProfile = require('./api-key/teacherProfile')
const teacherUpdate = require('./api-key/teacherProfileUpdate')
const teacherDelete = require('./api-key/teacherDelete')
const studentPortalSigin = require('./api-key/studentPortal')
const {main, room, AcademicExcellence, BMCSS1, library, portal, teacherimage, studentimage, studentPortal, teacherPortal, studentdisplay, transcript, feesportal, feesStructure, examportal, teacherportals, homework} = require('./api-key/main')
const authMidlewaretwo = require('./midlwire/sessiontwo')
const studentApi = require('./api-key/studentApi')
const studentlogout = require('./api-key/studentlogout')
const authMidlewarethree = require('./midlwire/sessionthree')
const teacherPortalSigin = require('./api-key/teacherprotal')
const teacherlogout = require('./api-key/teacherlogout')
const teacherdataget = require('./api-key/teacherlogin')
const homeworks = require('./api-key/teacherhomework')
const homeworkget = require('./api-key/displayhomeworl')
const homeworkupdate = require('./api-key/homeworkupdate')
const homeworkdelete = require('./api-key/homeworkdelete')
require('dotenv').config();


const app = express()
const url = process.env.MONGO_URL

connect(url)
.then(()=>{console.log('mdb connect')}).catch((error)=>{console.log('can not connect',error)})

app.use(cookiesParser())
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use('/uploads', express.static(path.join(__dirname, 'public', 'uploads')));

app.use('/submit',studentData)
app.use('/studentProfile',studentProfile)
app.use('/mark',mark)
app.use('/update',update)
app.use('/dateSheet',dateSheet)
app.use('/dateSheetTable',dateSheetTable)
app.use('/updateDateSheet',updateDateSheet)
app.use('/signup',signup)
app.use('/data',updatedata)
app.use('/delete',deletes)
app.use('/fees',fees)
app.use('/teacher',teacher)
app.use('/teacherSignup',teacherSignup)
app.use('/teacherProfile',teacherProfile)
app.use('/teacherProfile',teacherUpdate)
app.use('/teacherProfile',teacherDelete)
app.use('/studentPortalSigin',studentPortalSigin)
app.use('/studentApi',studentApi)
app.use('/studentdisplay',authMidlewaretwo,studentdisplay)
app.use('/studenthomework',authMidlewaretwo,studenthomework)
app.use('/transcript',authMidlewaretwo,transcript)
app.use('/feesportal',authMidlewaretwo,feesportal)
app.use('/feesStructure',feesStructure)
app.use('/examportal',authMidlewaretwo,examportal)
app.use('/teacherportals',authMidlewarethree,teacherportals)
app.use('/studentlogout',studentlogout)
app.use('/teacherdata',teacherdataget)
app.use('/homework',homework)
app.use('/homeworks',homeworks)
app.use('/homeworkget',homeworkget)
app.use('/homeworkupdate',homeworkupdate)
app.use('/homeworkdelete',homeworkdelete)

app.use(process.env.root,main)
app.use('/room',room)
app.use('/AcademicExcellence',AcademicExcellence)
app.use('/BMCSS1',BMCSS1)
app.use('/library',library)
app.use('/portal',portal)
app.use('/teachers',teacherimage)
app.use('/students',studentimage)
app.use('/studentPortal',studentPortal)
app.use('/teacherPortal',teacherPortal)
app.use('/auth',authpage)
app.use(process.env.admin,authMidleware,home)
app.use('/noumi',authMidleware,image)
app.use('/studentSection',authMidleware,studentSection)
app.use(process.env.sin,authMidleware,studentSignup)
app.use('/student',authMidleware,student)
app.use('/examSection',authMidleware,examSection)
app.use('/studentMark',authMidleware,studentMarks)
app.use('/examDateSheet',authMidleware,examDateSheet)
app.use('/feesSection',authMidleware,feesSection)
app.use('/manageFees',authMidleware,manageFees)
app.use('/teacherSection',authMidleware,teacherSection)
app.use('/teacherAccount',authMidleware,teacherAccount)
app.use('/allhomework',authMidlewarethree,allhomework)
app.use('/teacher',authMidleware,teacherdata)
app.use('/studentdisplay',studentdisplay)
app.use('/teacherlogin',teacherPortalSigin)
app.use('/teacherlogout',teacherlogout)
app.use('/auth',auth)


const PORT = process.env.PORT || 5000;

app.listen(PORT,()=>{console.log(`server is running on port no ${PORT}`)})